///@func Profile_Clean_Auto
///@desc Deletes all profiles marked as "autogenerated"
function Profile_Clean_Auto() {
	log("Number of Profiles ", ds_list_size(global.profiles));
	for(var i = 0; i < ds_list_size(global.profiles); i++)
		{
		if (Profile_Get(i, PROFILE.autogenerated))
			{
			Profile_Destroy(i);
			i--; 
			}
		}


}
